### ISSUE TITLE
[Inquiry] Unexplained "mod broken" notice with no additional context

### ISSUE THREAD

**Issue by Vectorial1024** [chameleon-tbn/CompatibilityReport#55]
Hi there!

This is a great mod to have for us players and modders alike to see whether we may potential problems with our mod setups.

However, with the recent release of the Plazas and promenades DLC, I have noticed that 2 of my mods, Express Bus Services (ID 2262054175) and Express Bus Services TLM Plugin (ID 2630529375) are marked as "broken" with no further details. This is seen in e.g. catalog version 5.94; I hlpe this info is helpful.

I checked the catalog file (which I guess is the file that is used for client mods to check things), and it says that both mods are "stable".

https://github.com/Finwickle/CompatibilityReport/blob/5c544aeeaccf408d1d2ab74203f47d472a859b68/CompatibilityReport_Catalog.xml

May I know what is going on? Having unexplained inaccuracies in a correctness mod can be fatal.

**Comment by chameleon-tbn** [comment]
Hei Vectorial, 

first, the file you link to is not the actual file. It is just the one delivered with the mod for installation :)
second, i have added a link both in the report and also on the workshop site to report wrong information :)
third, we are all humans - so errors can happen.

**Comment by chameleon-tbn** [comment]
But if you want an explanation:

first tests it ran against the wall as TLM was not updated - and at that time it was not clear if TLM or the plugin caused it. Therefore both where marked broken for the moment. But after TLM got updated, i simply have overseen to remove your plugin too. Se same was btw with the IPT plugin, but this is already back to stable status. And regarding to your main mod i can't tell right now if it is an interfere with maybe 81 Tiles 2 but at least in a combination with 130 other mods adding yours the game stopped working. As the launch used ofc a lot of my time i not had time to test all eventual cases. Therefore i needed to decide what to do. 

So in this case (as with some other mods) better save for the players and sorry for the modder. Esp. as i can handle way easier one modder complaining than 10k players complaining there game is not loading any more .... Sorry for that :)

The second plugin will get on stable with next catalog and now i have some more time, i can test the details of the issue

**Comment by chameleon-tbn** [comment]
Tested everything again this evening and night. Due to the other mods got fixed i'm not getting any error anymore. Catalog is already updated. Kind regards.

Please next time contact me on the official ways i offer for such :)

**Comment by Vectorial1024** [comment]
Ah, I also saw your update on the steam mod page, and everything seems to become clearer now. And the catalog I say it updated too.

Indeed, we are humans. I must also admit I basically ignored requests to check compatibility of my mods with 81 tiles until very recently...

------

Still, to try to make something nice out of this, perhaps we could store the "last checked" date for each mod entry in the catalog? That way, if we somehow are too busy to update/recheck the catalog, then users themselves may judge whether the catalog's judgement is good. Afterall, there gotta be some delay with updating the catalog, and mods might get updated while we are doing something else.

But ideally, the catalog got to have up to date information.

------

Still, many thanks for the update!

**Comment by chameleon-tbn** [comment]
You're very welcome. I think it is needed to explain more about testing.

In the very beginning all ~2000 mods where one time tested and categorised. Now every time a mod gets updated, new released or i get a report of issues regarding to it, it will be tested again the top 200 mods. Functionality is tested and logs get checked for any kind of errors. One day a week i updated the catalog.

Every time the game gets updated an additional test of the top 200 mods against new game version prior the release takes place. All of the top 200 mods with issues i either contact the creator or search or one other modder to work on a (temp) fix or new release. 

After the release the top 201-300 are added to the test. If there are issues they will be just flagged as broken, so the creator can see in CR that he should take of his mod(s) [Hey! It worked, you took care ;) ]. As soon as the creator either update his mod (i get automatically this info) or contact me using the report form or on the official discord channel for this, i add the mod back in the test and update the catalog in a short term. Short term in the case of a game update meant this time 11 catalog updates within 5 days.

Additionally all mods that are reported to cause issues using the form or discord are tested the same way too 

There are mods that will be most likely never tested again, as they have only a few subscribers, be rather old, and no one takes care - not even the creator. They will be only tested again if at least one report will come in or suddenly an update is pushed to workshop. 

Therefore the info of last test date seems not really very important for me - even a 7 year old mod can still run perfect. A last tested day would easily lead to the feeling: "It will Not Work". Additionally with more and more info it gets harder for the players to understand.

All the game update mod compatibility tests are done by me. Only the regular weekly mod releases are also checked by rlas who supports me. 

Just to make more clear what all this means: In the last three weeks i spent every day between 8-16 hours in testing, feedback, coordinating and support. The days since release i had support requests from ~450 players to get their game back running - additionally to the compatibility tests. Only arround 20 i could not bring back to life. 

In general players can be sure: all new mod releases and updates are tested within one week. 

And as creator you can be sure: your mod will be tested at release, at every update and if a user reports - in all these cases you'll be contacted if there is an issue. 

And in case of game updates your mods will be additionally tested in case it is in the top 200 in advance, in the top 300 at release. At game update it's the modders work to check if something is in the catalog about his mod. Easily done by subbing to his own mod and have a single look each day into the CR.

The plan for the next version of CR is to show an ingame popup in case a new catalog is available. This should remind players and creators in the same way.

Please feel free to contact me on Discord of you have further questions, i'll close that one here now.

Read you soon :)

**Comment by Vectorial1024** [comment]
Thanks for the writing! I never imagined how many work was put into maintaining the catalog. This is truly important work helping out the many many players! A lot of thought was made onto what to prioritize and what to show etc, this is true dedication.

To be honest, I only noticed my mod being marked as broken after reading user feedback; I was not paying attention to CSL every day. If there were no reports, then it might be "the mod is marked as broken but no one knew/cared and everyone forgot about the mod".

------

Good idea on the catalog update popup!

And maybe a very short summary of the prioritization can be posted in the new workshop page? So that everyone knows roughly what to expect and what to do to help out.

**Comment by chameleon-tbn** [comment]
With the new version to release with new ID, i'll add more such information.

**Comment by chameleon-tbn** [comment]
all done
